### ISSUE TITLE
Indenting using tabs instead of spaces

### ISSUE THREAD

**Issue by adl1995** [SublimeLinter/SublimeLinter-pep8#19]
I would like to know if it's possible to indent my Python code using tabs instead of spaces. If so, what do I need to add in the settings file?

**Comment by braver** [comment]
I think you need to ignore error code `W191`.

You should put configuration like this in a config file for the linter, not in a SublimeLinter configuration. Because it's not specific to this linter/editor implementation you're better off asking such questions on the Sublime forum or elsewhere: these repos aren't active enough for people to see your question.

http://pycodestyle.pycqa.org/en/latest/intro.html#configuration
